os: linux
language: dart
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-noto

before_script:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor

script:
  - ./flutter/bin/flutter build bundle

cache:
  directories:
    - $HOME/shared/.pub-cache